### ISSUE TITLE
Point on element id={}

### ISSUE THREAD

**Issue by mariaalouisaa** [fac24/week-5-Peter-Hussain#14]
https://github.com/fac24/week-5-Peter-Hussain/blob/6793aa8c2fb1425a69703c6b18c714a4cc03abee/game/src/components/GameCardContainer.jsx#L58-L59

I did this in one of the workshops. Where you are using key that is the index of the item in the array. The mentors mentioned this isn't great practice as if you remove something from the array all index of the items after that will change meaning your id's will change with them.

I also learnt (only yesterday) best practice to have a id starting with a numeric value 🥸

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by joe-dev-public** [comment]
Also, you might see this warning in your browser console: ``Warning: Each child in a list should have a unique "key" prop.``

So you'll probably want to set a ``key={key}`` attribute on each of these ``GameCard`` components.
